import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Droplet, Printer, ArrowLeft } from "lucide-react";
import { api } from "../api";

export default function CertificatePage() {
  const { donorId, entryId } = useParams();
  const [data, setData] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    api
      .get(`/api/donors/${donorId}/donations`)
      .then(setData)
      .catch((err) => setError(err.message));
  }, [donorId]);

  const entry = data?.donations.find((d) => d._id === entryId);

  return (
    <div style={{ background: "var(--bg)", minHeight: "100vh", padding: "24px 16px" }}>
      <div className="no-print" style={{ maxWidth: 760, margin: "0 auto 16px", display: "flex", justifyContent: "space-between" }}>
        <Link to="/profile" className="btn-outline" style={{ display: "inline-flex", alignItems: "center", gap: 6 }}>
          <ArrowLeft size={14} /> Back to profile
        </Link>
        {entry && (
          <button onClick={() => window.print()}>
            <Printer size={14} /> Print / Save as PDF
          </button>
        )}
      </div>

      {error && <p className="error" style={{ textAlign: "center" }}>{error}</p>}
      {data && !entry && <p className="status" style={{ textAlign: "center" }}>That donation record wasn't found.</p>}

      {entry && (
        <div
          className="certificate"
          style={{
            maxWidth: 760,
            margin: "0 auto",
            background: "#fff",
            border: "2px solid var(--primary)",
            borderRadius: 12,
            padding: "48px 40px",
            textAlign: "center",
          }}
        >
          <div className="sidebar-brand" style={{ justifyContent: "center", padding: 0, marginBottom: 20 }}>
            <span className="mark">
              <Droplet size={16} fill="currentColor" />
            </span>
            RaktSetu
          </div>

          <p className="section-kicker" style={{ marginBottom: 6 }}>Blood donation acknowledgement</p>
          <h1 style={{ fontSize: "1.9rem", marginBottom: 24 }}>Thank you, {data.donorName}</h1>

          <p style={{ fontSize: "1.05rem", lineHeight: 1.7, maxWidth: "52ch", margin: "0 auto" }}>
            This acknowledges that <strong>{data.donorName}</strong> (blood group <strong>{entry.bloodGroup}</strong>)
            donated blood on{" "}
            <strong>{new Date(entry.date).toLocaleDateString(undefined, { dateStyle: "long" })}</strong>
            {entry.hospital && (
              <>
                {" "}
                for a request at <strong>{entry.hospital}</strong>
                {entry.area && <>, {entry.area}</>}
              </>
            )}
            , through RaktSetu.
          </p>

          <p style={{ marginTop: 28, fontWeight: 600, color: "var(--primary)" }}>
            A donation like this can help save up to three lives.
          </p>

          <p
            style={{
              marginTop: 36,
              paddingTop: 16,
              borderTop: "1px solid var(--border)",
              fontSize: "0.75rem",
              color: "var(--text-soft)",
              lineHeight: 1.5,
            }}
          >
            Generated by RaktSetu from donation records confirmed by the requesting family. This is a
            personal acknowledgement, not an official blood bank certificate. For employer blood-donation
            leave or any legal purpose, please obtain the official certificate from the blood bank or
            hospital that collected the donation.
          </p>
        </div>
      )}
    </div>
  );
}
